import Game.Metadata

World "CyclicGroups"
Level 4

Title "When zpowers is Trivial"

Introduction
"
When is `zpowers g` the trivial subgroup `⊥`? Only when `g` is
the identity:

`Subgroup.zpowers_eq_bot : zpowers g = ⊥ ↔ g = 1`

This makes sense: `zpowers 1 = {1^k | k ∈ ℤ} = {1} = ⊥`, and
if `g ≠ 1`, then `g ∈ zpowers g` but `g ∉ ⊥`.

Given that `zpowers g = ⊥`, extract the consequence `g = 1`.
"

/-- `Subgroup.zpowers_eq_bot` says:

`zpowers g = ⊥ ↔ g = 1`

The subgroup generated by `g` is trivial if and only if `g` is
the identity.

Use `rw [Subgroup.zpowers_eq_bot] at h` to convert a hypothesis
`h : zpowers g = ⊥` into `h : g = 1`. -/
TheoremDoc Subgroup.zpowers_eq_bot as "Subgroup.zpowers_eq_bot" in "Cyclic"

NewTheorem Subgroup.zpowers_eq_bot

TheoremTab "Cyclic"

DisabledTactic group

Statement (G : Type*) [Group G] (g : G) (h : Subgroup.zpowers g = ⊥) :
    g = 1 := by
  Hint "The hypothesis `h : zpowers {g} = ⊥` tells you that the
  subgroup generated by `{g}` is trivial. Use
  `rw [Subgroup.zpowers_eq_bot] at h` to convert this to `{g} = 1`."
  rw [Subgroup.zpowers_eq_bot] at h
  Hint (hidden := true) "The hypothesis is now `h : {g} = 1`.
  Use `exact h`."
  exact h

Conclusion
"
`Subgroup.zpowers_eq_bot` lets you move between \"the subgroup
generated by `g` is trivial\" and \"`g` is the identity.\" You'll
use this in the boss level to rule out the trivial case.

The contrapositive is equally important: if `g ≠ 1`, then
`zpowers g ≠ ⊥` — the subgroup generated by a non-identity element
is always non-trivial. You'll use this reasoning in later levels
to rule out the trivial case by contradiction.
"
