import Game.Levels.CyclicGroups.L01_ZpowBasics
import Game.Levels.CyclicGroups.L02_ZpowersMem
import Game.Levels.CyclicGroups.L03_Decide
import Game.Levels.CyclicGroups.L04_ZpowersEqBot
import Game.Levels.CyclicGroups.L05_OrderOf
import Game.Levels.CyclicGroups.L06_IsCyclic
import Game.Levels.CyclicGroups.L07_PrimeDichotomy
import Game.Levels.CyclicGroups.L08_ZpowersTopOfPrime
import Game.Levels.CyclicGroups.L09_Boss

World "CyclicGroups"
Title "Cyclic Groups"
Introduction
"
What is the simplest kind of group? One answer: a group generated
by a single element. Such groups are called **cyclic**.

The integers `ℤ` (generated by `1`) and the clock group `ℤ/nℤ`
(generated by `1 mod n`) are the prototypical examples. But cyclic
groups show up in unexpected places: every group of **prime order**
is forced to be cyclic, regardless of how it was defined.

This world introduces three key concepts:

1. **Integer powers** `a ^ (k : ℤ)` — extending natural-number
   powers to negative exponents via `a ^ (-n) = (a ^ n)⁻¹`.

2. **zpowers** `Subgroup.zpowers g` — the subgroup generated by
   a single element, consisting of all integer powers of `g`.

3. **Order** `orderOf g` — the smallest positive `n` such that
   `g ^ n = 1`, measuring the \"period\" of an element.

The gateway theorem connecting these: a group is cyclic
(`IsCyclic G`) exactly when some element's zpowers equals the
whole group (`∃ g, zpowers g = ⊤`).

By the boss level, you'll prove that **every group of prime order
is cyclic** — the fundamental structural result that drives
classification of finite groups.

Two new tactics appear:
- `decide` — closes goals that are computationally verifiable
- `exfalso` — reduces any goal to `False` for contradiction arguments
"
