import Game.Metadata

World "NormalDef"
Level 4

Title "Membership Commutes"

Introduction
"
Here's a useful consequence of normality: if `a * b ∈ N` and `N` is
normal, then `b * a ∈ N` too.

The proof uses conjugation by `a⁻¹`:

`a⁻¹ * (a * b) * (a⁻¹)⁻¹ = a⁻¹ * (a * b) * a`

The inner part simplifies: `a⁻¹ * (a * b) = b` by `inv_mul_cancel_left`.
And `(a⁻¹)⁻¹ = a` by `inv_inv`. So the conjugate is `b * a`.

Use `have` to store the conjugation result, then simplify.
"

/-- `conj_mem'` is the reverse-conjugation variant:

`hN.conj_mem' n hn g : g⁻¹ * n * g ∈ N`

where `hN : N.Normal`, `hn : n ∈ N`, and `g : G`.

Use this when the conjugator appears inverted. -/
TheoremDoc Subgroup.Normal.conj_mem' as "conj_mem'" in "Normal"

/-- Disabled — you are proving this. -/
TheoremDoc Subgroup.Normal.mem_comm as "mem_comm" in "Normal"

/-- Disabled — you are proving this. -/
TheoremDoc Subgroup.Normal.mem_comm_iff as "mem_comm_iff" in "Normal"

NewTheorem Subgroup.Normal.conj_mem'

TheoremTab "Normal"

DisabledTactic simp group
DisabledTheorem Subgroup.Normal.mem_comm Subgroup.Normal.mem_comm_iff

Statement (G : Type*) [Group G] (N : Subgroup G) (hN : N.Normal)
    (a b : G) (hab : a * b ∈ N) : b * a ∈ N := by
  Hint "Use `have` to conjugate `a * b` by `a⁻¹`:
  `have h := hN.conj_mem (a * b) hab a⁻¹`."
  Branch
    have h := hN.conj_mem' (a * b) hab a
    Hint "You used `conj_mem'` with conjugator `a`. Now
    `{h} : a⁻¹ * (a * b) * a ∈ N`. Clean up the left:
    `rw [inv_mul_cancel_left] at {h}`."
    rw [inv_mul_cancel_left] at h
    Hint (hidden := true) "Now `{h} : b * a ∈ N`. `exact {h}`."
    exact h
  Branch
    have h := hN.conj_mem (a * b) hab b
    Hint "You conjugated by `b`. Now `{h} : b * (a * b) * b⁻¹ ∈ N`.
    Simplify step by step:
    `rw [mul_assoc, mul_assoc, mul_inv_cancel, mul_one] at {h}`."
    rw [mul_assoc, mul_assoc, mul_inv_cancel, mul_one] at h
    Hint (hidden := true) "Now `{h} : b * a ∈ N`. `exact {h}`."
    exact h
  have h := hN.conj_mem (a * b) hab a⁻¹
  Hint "Now `{h} : a⁻¹ * (a * b) * (a⁻¹)⁻¹ ∈ N`. Clean it up:
  `rw [inv_inv, inv_mul_cancel_left] at {h}`."
  rw [inv_inv, inv_mul_cancel_left] at h
  Hint (hidden := true) "Now `{h} : b * a ∈ N`. `exact {h}`."
  exact h

Conclusion
"
Normality makes multiplication order irrelevant for membership:
`a * b ∈ N ↔ b * a ∈ N`.

The proof uses the **conjugate-then-cancel** pattern: apply `conj_mem`
with a strategic conjugator, store via `have`, then simplify.

On paper: *Since `ab ∈ N` and `N` is normal, conjugate by `a⁻¹`:
`a⁻¹(ab)(a⁻¹)⁻¹ = a⁻¹(ab)a = ba ∈ N`.*

Looking ahead: this result hints at something deeper. The element
`a⁻¹b⁻¹ab` is called a **commutator** — it measures how far `a` and
`b` are from commuting. If `a⁻¹b⁻¹ab ∈ N` for all `a, b`, then
`ab` and `ba` always land in the same coset of `N`, making `G/N`
abelian. The subgroup generated by all commutators is central to
understanding when quotients are abelian.
"
