import Game.Levels.CountingPset.L01_FreshCounting
import Game.Levels.CountingPset.L02_FreshPigeonhole
import Game.Levels.CountingPset.L03_CardinalityComparison
import Game.Levels.CountingPset.L04_NonemptinessArgument
import Game.Levels.CountingPset.L05_TransferPigeonhole
import Game.Levels.CountingPset.L06_TransferCounting
import Game.Levels.CountingPset.L07_Boss
