import Game.Levels.FinsetTransformations.L01_Filter
import Game.Levels.FinsetTransformations.L02_MemFilterRewriting
import Game.Levels.FinsetTransformations.L03_Image
import Game.Levels.FinsetTransformations.L04_ImageWitness
import Game.Levels.FinsetTransformations.L05_MapVsImage
import Game.Levels.FinsetTransformations.L06_ComposingFilterImage
import Game.Levels.FinsetTransformations.L07_ImageShrinksCardinality
import Game.Levels.FinsetTransformations.L08_Boss
