import Game.Levels.FinsetSum.L01_WhatIsFinsetSum
import Game.Levels.FinsetSum.L02_SumEmpty
import Game.Levels.FinsetSum.L03_SumSingleton
import Game.Levels.FinsetSum.L04_SumCons
import Game.Levels.FinsetSum.L05_SumInsert
import Game.Levels.FinsetSum.L06_AddCommMonoid
import Game.Levels.FinsetSum.L07_ConcreteSum
import Game.Levels.FinsetSum.L08_SumUnion
import Game.Levels.FinsetSum.L09_Boss
