import Game.Levels.ListUnderLenses.L01_ListPerspective
import Game.Levels.ListUnderLenses.L02_MultisetPerspective
import Game.Levels.ListUnderLenses.L03_FinsetPerspective
import Game.Levels.ListUnderLenses.L04_ReorderingInvariance
import Game.Levels.ListUnderLenses.L05_MapPreservesCard
import Game.Levels.ListUnderLenses.L06_Boss
