import Game.Levels.ListBasics.L01_ListCons
import Game.Levels.ListBasics.L02_ListLength
import Game.Levels.ListBasics.L03_ListMem
import Game.Levels.ListBasics.L04_MemAppend
import Game.Levels.ListBasics.L05_ListMap
import Game.Levels.ListBasics.L06_ListFilter
import Game.Levels.ListBasics.L07_AppendLength
import Game.Levels.ListBasics.L08_FinIndexing
import Game.Levels.ListBasics.L09_Nodup
import Game.Levels.ListBasics.L10_Practice
import Game.Levels.ListBasics.L11_Boss
