import Game.Levels.PermutationWorld.L01_PermDef
import Game.Levels.PermutationWorld.L02_ConcreteSwap
import Game.Levels.PermutationWorld.L03_Composition
import Game.Levels.PermutationWorld.L04_Identity
import Game.Levels.PermutationWorld.L05_CountingPerms
import Game.Levels.PermutationWorld.L06_ListPermVsEquivPerm
import Game.Levels.PermutationWorld.L07_Boss
