import Game.Metadata

World "CyclicGroups"
Level 2

Title "The Subgroup Generated by One Element"

Introduction
"
Given an element `g` of a group `G`, the set of all integer powers
of `g` forms a subgroup. This subgroup is called `Subgroup.zpowers g`:

`zpowers g = {x : G | ∃ k : ℤ, g ^ k = x}`

It is the smallest subgroup containing `g` — the subgroup *generated*
by `g`.

The key membership lemma is `Subgroup.mem_zpowers_iff`:

`h ∈ zpowers g ↔ ∃ k : ℤ, g ^ k = h`

To show `h ∈ zpowers g`, rewrite with `mem_zpowers_iff` and then
provide the integer exponent that works.

**Warning**: The `^` in this world is integer power (`zpow`), not the
natural-number `^` from CommGroupIntro. They look identical but are
different operations internally. In particular, `pow_one` does **not**
apply to `g ^ (1 : ℤ)` — you need `zpow_one` instead. If you see
a confusing \"did not find occurrence\" error after `rw [pow_one]`,
that's why. Always use the `zpow_*` lemmas for integer exponents.

Prove that `g⁻¹` is in `zpowers g` by finding the right exponent.
"

/-- The subgroup `Subgroup.zpowers g` is the subgroup generated by a
single element `g`:

`zpowers g = {x : G | ∃ k : ℤ, g ^ k = x}`

It contains all integer powers of `g`: `g⁰ = 1`, `g¹ = g`,
`g⁻¹`, `g²`, `g⁻²`, and so on.

This is the fundamental building block for cyclic groups — a group
is cyclic exactly when some element's zpowers equals the whole group. -/
DefinitionDoc Subgroup.zpowers as "Subgroup.zpowers"

NewDefinition Subgroup.zpowers

/-- `Subgroup.mem_zpowers_iff` says:

`h ∈ zpowers g ↔ ∃ k : ℤ, g ^ k = h`

To show `h ∈ zpowers g`, rewrite the goal with
`rw [Subgroup.mem_zpowers_iff]`, then provide the witness `k`
with `refine ⟨k, ?_⟩` or `exact ⟨k, proof⟩`. -/
TheoremDoc Subgroup.mem_zpowers_iff as "Subgroup.mem_zpowers_iff" in "Cyclic"

-- zpow_mem_zpowers and mem_zpowers are one-shot bypasses; disable them
-- so the learner must use mem_zpowers_iff and provide the witness.
/-- `Subgroup.zpow_mem_zpowers g k` says `g ^ k ∈ zpowers g`.
Disabled here so you practice `mem_zpowers_iff` instead. -/
TheoremDoc Subgroup.zpow_mem_zpowers as "Subgroup.zpow_mem_zpowers" in "Cyclic"
/-- `Subgroup.mem_zpowers g` says `g ∈ zpowers g`.
Disabled here so you practice `mem_zpowers_iff` instead. -/
TheoremDoc Subgroup.mem_zpowers as "Subgroup.mem_zpowers" in "Cyclic"

NewTheorem Subgroup.mem_zpowers_iff

TheoremTab "Cyclic"

DisabledTactic group
DisabledTheorem InvMemClass.inv_mem Subgroup.zpow_mem_zpowers Subgroup.mem_zpowers

Statement (G : Type*) [Group G] (g : G) :
    g⁻¹ ∈ Subgroup.zpowers g := by
  Hint "Use `rw [Subgroup.mem_zpowers_iff]` to convert the goal to
  `∃ k : ℤ, g ^ k = g⁻¹`."
  rw [Subgroup.mem_zpowers_iff]
  Hint "You need to find a `k : ℤ` such that `g ^ k = {g}⁻¹`.
  Since `g ^ (-1 : ℤ) = g⁻¹` (by `zpow_neg` and `zpow_one`),
  the witness is `-1`.

  Use `refine ⟨-1, ?_⟩` to provide the witness and leave the
  proof as a subgoal."
  refine ⟨-1, ?_⟩
  Hint "The goal is `{g} ^ (-1 : ℤ) = {g}⁻¹`. Use `zpow_neg` and
  `zpow_one` to simplify the left side."
  Hint (hidden := true) "`rw [zpow_neg, zpow_one]`"
  rw [zpow_neg, zpow_one]

Conclusion
"
You proved `g⁻¹ ∈ zpowers g` by finding the exponent `-1`.

The proof pattern for zpowers membership is:

1. `rw [Subgroup.mem_zpowers_iff]` — convert to `∃ k, g ^ k = h`
2. `refine ⟨k, ?_⟩` — provide the witness integer
3. simplify `g ^ k` using `zpow_zero`, `zpow_one`, `zpow_neg`, etc.

Since `zpowers g` contains all integer powers of `g`, it contains
`g` itself (exponent `1`), `1` (exponent `0`), `g⁻¹` (exponent `-1`),
`g²` (exponent `2`), and so on.

The notation `⟨k, proof⟩` for `∃` witnesses works like the
angle-bracket notation you already know for `∧` — the first component
is the witness, the second is the proof that the witness works.
"
