import Game.Metadata

World "CyclicGroups"
Level 6

Title "Cyclic Groups"

Introduction
"
A group is **cyclic** if some single element generates the entire
group — that is, every element can be written as an integer power
of the generator.

In Lean, this is the typeclass `IsCyclic G`. The characterization
in terms of `zpowers` is:

`isCyclic_iff_exists_zpowers_eq_top : IsCyclic G ↔ ∃ g, zpowers g = ⊤`

A group is cyclic if and only if there exists an element whose
zpowers subgroup is the whole group.

Given that `zpowers g = ⊤` (i.e., `g` generates the whole group),
prove `IsCyclic G`.
"

/-- A group `G` is **cyclic**, written `IsCyclic G`, if some element
generates the whole group: every element is an integer power of the
generator.

Use `rw [isCyclic_iff_exists_zpowers_eq_top]` to convert `IsCyclic G`
to `∃ g, zpowers g = ⊤`. -/
DefinitionDoc IsCyclic as "IsCyclic"

NewDefinition IsCyclic

/-- `isCyclic_iff_exists_zpowers_eq_top` says:

`IsCyclic G ↔ ∃ g, zpowers g = ⊤`

A group is cyclic if and only if some element's zpowers subgroup
equals the whole group.

Use `rw [isCyclic_iff_exists_zpowers_eq_top]` to unfold
`IsCyclic G` in the goal. -/
TheoremDoc isCyclic_iff_exists_zpowers_eq_top as "isCyclic_iff_exists_zpowers_eq_top" in "Cyclic"

NewTheorem isCyclic_iff_exists_zpowers_eq_top

TheoremTab "Cyclic"

/-- Disabled — you'll prove this in the boss level. -/
TheoremDoc isCyclic_of_prime_card as "isCyclic_of_prime_card" in "Cyclic"

DisabledTactic group
DisabledTheorem isCyclic_of_prime_card

Statement (G : Type*) [Group G] (g : G) (hg : Subgroup.zpowers g = ⊤) :
    IsCyclic G := by
  Hint "Convert `IsCyclic G` to its zpowers characterization:
  `rw [isCyclic_iff_exists_zpowers_eq_top]`."
  rw [isCyclic_iff_exists_zpowers_eq_top]
  Hint "The goal is `∃ g', zpowers g' = ⊤`. Provide `{g}` as the
  generator and `hg` as the proof: `exact ⟨{g}, hg⟩`."
  Hint (hidden := true) "`exact ⟨{g}, hg⟩`"
  exact ⟨g, hg⟩

Conclusion
"
You proved that if `zpowers g = ⊤`, then the group is cyclic. The
proof had two steps:

1. `IsCyclic G` ↔ `∃ g, zpowers g = ⊤` (by `isCyclic_iff_exists_zpowers_eq_top`)
2. Provide the witness `g` and the proof `hg`

On paper: *\"A group is cyclic if some element generates it. `g`
generates `G` because `zpowers g = G`.\"*

The familiar examples of cyclic groups are `ℤ` (generated by `1`)
and `ℤ/nℤ` (generated by `1 mod n`). In the boss level, you'll
prove something stronger: every group of **prime** order is cyclic.
The key will be showing `zpowers g = ⊤` for any non-identity `g`.
"
