import Game.Metadata

World "CyclicGroups"
Level 9

Title "Boss — Prime-Order Groups Are Cyclic"

Introduction
"
Prove the crown jewel of this world: **every group of prime order
is cyclic**.

More precisely: if the cardinality of `G` is prime and `g ≠ 1`,
then `g` generates `G` — every element is in `zpowers g`.

Your toolkit:

| Tool | Purpose |
|------|---------|
| `isCyclic_iff_exists_zpowers_eq_top` | Convert `IsCyclic G` to `∃ g, zpowers g = ⊤` |
| `refine ⟨g, ?_⟩` | Provide the generator witness |
| `H.eq_bot_or_eq_top_of_prime_card` | Get `H = ⊥ ∨ H = ⊤` in prime-order group |
| `obtain hbot \\| htop` | Case-split the disjunction |
| `Subgroup.zpowers_eq_bot` | Convert `zpowers g = ⊥` to `g = 1` |
| `exfalso` | Reduce to `False` when hypotheses contradict |

Strategy:
1. Unfold `IsCyclic G` to `∃ g, zpowers g = ⊤`
2. Provide `g` as the generator
3. Apply the prime-order dichotomy to get `zpowers g = ⊥ ∨ ⊤`
4. Rule out `⊥` using `g ≠ 1`
"

TheoremTab "Cyclic"

DisabledTactic group

/-- Disabled — prove it yourself using the prime-order dichotomy. -/
TheoremDoc mem_zpowers_of_prime_card as "mem_zpowers_of_prime_card" in "Cyclic"

/-- Disabled — this is the result you're proving. -/
TheoremDoc isCyclic_of_prime_card as "isCyclic_of_prime_card" in "Cyclic"

/-- Disabled — prove it yourself. -/
TheoremDoc zpowers_eq_top_of_prime_card as "zpowers_eq_top_of_prime_card" in "Cyclic"

/-- Disabled — prove it yourself. -/
TheoremDoc isCyclic_of_card_dvd_prime as "isCyclic_of_card_dvd_prime" in "Cyclic"

DisabledTheorem isCyclic_of_prime_card zpowers_eq_top_of_prime_card mem_zpowers_of_prime_card isCyclic_of_card_dvd_prime

Statement (G : Type*) [Group G] [Fact (Nat.card G).Prime]
    (g : G) (hg : g ≠ 1) : IsCyclic G := by
  Hint "Start by converting `IsCyclic G` to its zpowers
  characterization: `rw [isCyclic_iff_exists_zpowers_eq_top]`."
  rw [isCyclic_iff_exists_zpowers_eq_top]
  Hint "Provide `{g}` as the generator:
  `refine ⟨{g}, ?_⟩`."
  refine ⟨g, ?_⟩
  Hint "The goal is `zpowers {g} = ⊤`. In a prime-order group,
  every subgroup is either `⊥` or `⊤`. Get this disjunction:

  `obtain hbot | htop := (Subgroup.zpowers {g}).eq_bot_or_eq_top_of_prime_card`"
  obtain hbot | htop := (Subgroup.zpowers g).eq_bot_or_eq_top_of_prime_card
  · Hint "**Case** `hbot : zpowers {g} = ⊥`: this means `{g} = 1`
    by `zpowers_eq_bot`. But `hg : {g} ≠ 1` — contradiction.

    Use `rw [Subgroup.zpowers_eq_bot] at hbot` to convert."
    rw [Subgroup.zpowers_eq_bot] at hbot
    Hint "Now `hbot : {g} = 1` contradicts `hg : {g} ≠ 1`.
    Use `exfalso` then `exact hg hbot`."
    exfalso
    exact hg hbot
  · Hint "**Case** `htop : zpowers {g} = ⊤`: this is exactly
    the goal."
    Hint (hidden := true) "`exact htop`"
    exact htop

Conclusion
"
Congratulations on completing **Cyclic Groups**!

You proved the cornerstone result: **a group of prime order is
cyclic**. Any non-identity element generates the entire group.

The proof is the **dichotomy-plus-contradiction** pattern applied
to `zpowers g`:
1. In a prime-order group, every subgroup is `⊥` or `⊤`
   (Lagrange + primality)
2. `zpowers g` is a subgroup, so `zpowers g = ⊥ ∨ zpowers g = ⊤`
3. If `zpowers g = ⊥`, then `g = 1` (by `zpowers_eq_bot`) —
   contradiction with `g ≠ 1`
4. So `zpowers g = ⊤` — `g` generates `G`
5. Therefore `G` is cyclic

On paper: *\"Let `|G| = p` be prime, and let `g ∈ G` with `g ≠ 1`.
The subgroup `⟨g⟩` generated by `g` has order dividing `p`, so its
order is `1` or `p`. Since `g ≠ 1`, the order is not `1`, so it
must be `p`. Therefore `⟨g⟩ = G` and `G` is cyclic.\"*

**Caution**: the converse is false. Not every cyclic group has prime
order — `ℤ` is cyclic with infinite order, and `ℤ/6ℤ` is cyclic
with non-prime order. Prime order *implies* cyclic, but cyclic does
not imply prime order.

Your new tools from this world:

| Item | Type | Purpose |
|------|------|---------|
| `zpow_zero`, `zpow_one`, `zpow_neg` | Theorem | Integer power identities |
| `Subgroup.zpowers g` | Definition | Subgroup generated by `g` |
| `Subgroup.mem_zpowers_iff` | Theorem | `h ∈ zpowers g ↔ ∃ k, g^k = h` |
| `Subgroup.zpowers_eq_bot` | Theorem | `zpowers g = ⊥ ↔ g = 1` |
| `orderOf g` | Definition | Order of an element |
| `pow_orderOf_eq_one` | Theorem | `g ^ orderOf g = 1` |
| `IsCyclic G` | Definition | `G` is cyclic |
| `isCyclic_iff_exists_zpowers_eq_top` | Theorem | `IsCyclic G ↔ ∃ g, zpowers g = ⊤` |
| `eq_bot_or_eq_top_of_prime_card` | Theorem | Prime order ⇒ subgroups are ⊥ or ⊤ |
| `decide` | Tactic | Close decidable goals |
| `exfalso` | Tactic | Reduce any goal to `False` |

The result you proved — groups of prime order are cyclic — will
reappear in the **Lagrange** world, where you'll prove that
prime-order groups have no nontrivial proper subgroups. It also
drives the classification of small groups via **Sylow theory**.
"
